biqguery-data-engineering-zoomcamp:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: ./.keys/astral-pursuit-422621-e6-4789763eb8fa.json
      project: taxi-rides-ny
      dataset: dbt_armand_winant
      threads: 4
      location: EU